# Project information
site_name: Пишем Telegram-ботов с aiogram 3.x
site_description: Учебник по разработке ботов для Telegram на языке Python при помощи фреймворка aiogram 3.x
site_author: MasterGroosha
site_url: https://mastergroosha.github.io/aiogram-3-guide
docs_dir: book_src
site_dir: docs

# Repository
repo_name: MasterGroosha/aiogram-3-guide
repo_url: https://github.com/MasterGroosha/aiogram-3-guide
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020-2025 Groosha

# Configuration
theme:
  name: material
  custom_dir: book_src/overrides
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Включить тёмную тему
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Включить светлую тему
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/robot
#  features:
#    - navigation.expand

# Extras
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/+DE0_2nCvbXozZjUy
      name: "Чат в Telegram"
    - icon: fontawesome/brands/github
      link: https://github.com/MasterGroosha/aiogram-3-guide
      name: GitHub
  announcement: Кажется эта страница не была переведена на этот Язык и предварительно будет показана на Русском Языке.
  translation_warning_string: Информация о переводе
  translation_in_work_string: |
    👋 Приветствую! Я, <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>, работаю над переводом этой страницы.
    Контент находится в процессе перевода и может содержать неточности. Если вы заметите ошибки или хотите помочь, 
    пожалуйста, создайте issue или pull request на <a href="https://github.com/MasterGroosha/aiogram-3-guide">GitHub</a>.
  translation_stopped_string: |
    ⚠️ Внимание! Я, <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>, хочу сообщить, что 
    перевод этой страницы временно приостановлен. Вы можете видеть частично переведенный контент или оригинальный текст на русском.
    Буду благодарен за помощь в завершении перевода.
  translation_need_help: |
    🆘 Нужна помощь с переводом! Эта страница содержит сложную техническую терминологию, 
    и я, <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>, ищу помощников для проверки 
    качества перевода. Если вы владеете обоими языками и разбираетесь в aiogram, 
    буду признателен за содействие через <a href="https://github.com/MasterGroosha/aiogram-3-guide">GitHub</a>.
  translation_complete_besides_photo: |
    ✅ Текст этой страницы полностью переведен мной, <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>, 
    но некоторые изображения и скриншоты могут быть всё ещё на русском языке. Работа над локализацией 
    визуальных элементов продолжается. Спасибо за понимание!
  translator_unical_paper: |
    🌟 Уникальный контент! Эта страница создана мной, <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>, 
    специально для дополнения оригинального руководства. Она содержит информацию, которой нет в русской версии, 
    и призвана помочь англоязычным разработчикам лучше освоить aiogram 3.x. Буду рад вашим отзывам и предложениям!
  help_translation_cta: Помогите с переводом
    

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.blocks.details
  - meta
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - 'Введение': index.md
  - 'Знакомство с aiogram': quickstart.md
  - 'Работа с сообщениями': messages.md
  - 'Кнопки': buttons.md
  - 'Роутеры. Структура': routers.md
  - 'Фильтры и мидлвари': filters-and-middlewares.md
  - 'Особые апдейты': special-updates.md
  - 'Конечные автоматы': fsm.md
  - 'Инлайн-режим': inline-mode.md
  - 'Платежи': payments.md
  - '🔒 Продвинутый уровень': advanced-teaser.md
#  - 'Дополнительное чтение':
#    - 'Тест': extra/test.md


plugins:
  - mkdocs-video:
      is_video: True
      video_autoplay: False
      video_type: mp4
      css_style:
        width: "100%"
        height: "100%"
  - search:
      lang:
        - en
        - ru
  - i18n:
      reconfigure_material: true
      reconfigure_search: true
      docs_structure: folder
      languages:
        - locale: ru
          name: Русский
          default: true
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            'Введение': "Introduction"
            'Знакомство с aiogram': "Getting Started with aiogram"
            'Работа с сообщениями': "Working with Messages"
            'Кнопки': "Buttons"
            'Роутеры. Структура': "Routers. Structure"
            'Фильтры и мидлвари': "Filters and Middlewares"
            'Особые апдейты': "Special Updates"
            'Конечные автоматы': "Finite State Machines"
            'Инлайн-режим': "Inline Mode"
            'Платежи': "Payments"
            '🔒 Продвинутый уровень': "🔒 Advanced Level"
          nav_name: "Contents"
          site_name: Writing Telegram Bots with aiogram 3.x
          site_description: A tutorial on developing bots for Telegram using the aiogram 3.x framework in Python
          theme:
            name: material
            custom_dir: book_src/overrides
            language: en
            palette:
              - media: "(prefers-color-scheme: light)"
                scheme: default
                primary: purple
                toggle:
                  icon: material/brightness-4
                  name: Switch to Dark Theme
              - media: "(prefers-color-scheme: dark)"
                scheme: slate
                primary: purple
                toggle:
                  icon: material/brightness-7
                  name: Switch to Light Theme
            font:
              text: Roboto
              code: Roboto Mono
            icon:
              logo: material/robot
          extra:
            social:
              - icon: fontawesome/brands/telegram
                link: https://t.me/+DE0_2nCvbXozZjUy
                name: "Chat in Telegram"
              - icon: fontawesome/brands/github
                link: https://github.com/MasterGroosha/aiogram-3-guide
                name: GitHub
            announcement: It seems this page has not been translated into this Language and will preliminarily be displayed in Russian.
            translation_warning_string: Translation Information
            translation_in_work_string: |
              👋 Hello! I'm <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>, and I'm working on translating this page.
              This content is in the process of translation and may contain inaccuracies. If you notice any errors or want to help,
              please create an issue or pull request on <a href="https://github.com/MasterGroosha/aiogram-3-guide">GitHub</a>.
            translation_stopped_string: |
              ⚠️ Attention! I, <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>, want to inform you that
              translation of this page is temporarily suspended. You may see partially translated content or original Russian text.
              I would appreciate help in completing the translation.
            translation_need_help: |
              🆘 Translation help needed! This page contains complex technical terminology, 
              and I, <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>, am looking for help in verifying 
              the quality of the translation. If you are fluent in both languages and familiar with aiogram, 
              I would appreciate your assistance via <a href="https://github.com/MasterGroosha/aiogram-3-guide">GitHub</a>.
            translation_complete_besides_photo: |
              ✅ The text on this page has been fully translated by me, <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>, 
              but some images and screenshots may still be in Russian. Work on localizing 
              visual elements continues. Thank you for your understanding!
            translator_unical_paper: |
              🌟 Unique content! This page was created by me, <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>, 
              specifically to supplement the original guide. It contains information not present in the Russian version 
              and aims to help English-speaking developers better understand aiogram 3.x. I welcome your feedback and suggestions!
            help_translation_cta: Help with Translation
        - locale: uk
          name: Українська
          build: false
          nav_translations:
            'Введение': "Вступ"
            'Знакомство с aiogram': "Знайомство з aiogram"
            'Работа с сообщениями': "Робота з повідомленнями"
            'Кнопки': "Кнопки"
            'Роутеры. Структура': "Роутери. Структура"
            'Фильтры и мидлвари': "Фільтри та мідлвари"
            'Особые апдейты': "Особливі оновлення"
            'Конечные автоматы': "Кінцеві автомати"
            'Инлайн-режим': "Інлайн-режим"
            'Платежи': "Платежі"
            '🔒 Продвинутый уровень': "🔒 Просунутий рівень"
          nav_name: "Зміст"
          site_name: Написання ботів для Telegram з aiogram 3.x
          site_description: Посібник з розробки ботів для Telegram за допомогою фреймворку aiogram 3.x на Python
          theme:
            name: material
            custom_dir: book_src/overrides
            language: uk
            palette:
              - media: "(prefers-color-scheme: light)"
                scheme: default
                primary: purple
                toggle:
                  icon: material/brightness-4
                  name: Перемкнути на темну тему
              - media: "(prefers-color-scheme: dark)"
                scheme: slate
                primary: purple
                toggle:
                  icon: material/brightness-7
                  name: Перемкнути на світлу тему
            font:
              text: Roboto
              code: Roboto Mono
            icon:
              logo: material/robot
          extra:
            social:
              - icon: fontawesome/brands/telegram
                link: https://t.me/+DE0_2nCvbXozZjUy
                name: "Чат у Telegram"
              - icon: fontawesome/brands/github
                link: https://github.com/MasterGroosha/aiogram-3-guide
                name: GitHub
            announcement: Здається, ця сторінка ще не перекладена на цю мову і попередньо буде відображена російською.
            translation_warning_string: Інформація про переклад
            translation_in_work_string: |
              👋 Вітаю! Я, <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>, працюю над перекладом цієї сторінки.
              Контент знаходиться у процесі перекладу і може містити неточності. Якщо ви помітили помилки або хочете допомогти,
              будь ласка, створіть issue або pull request на <a href="https://github.com/MasterGroosha/aiogram-3-guide">GitHub</a>.
            translation_stopped_string: |
              ⚠️ Увага! Я, <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>, хочу повідомити, що
              переклад цієї сторінки тимчасово призупинено. Ви можете бачити частково перекладений контент або оригінальний текст російською.
              Буду вдячний за допомогу в завершенні перекладу.
            translation_need_help: |
              🆘 Потрібна допомога з перекладом! Ця сторінка містить складну технічну термінологію,
              і я, <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>, шукаю помічників для перевірки
              якості перекладу. Якщо ви володієте обома мовами та розбираєтеся в aiogram,
              буду вдячний за сприяння через <a href="https://github.com/MasterGroosha/aiogram-3-guide">GitHub</a>.
            translation_complete_besides_photo: |
              ✅ Текст цієї сторінки повністю перекладено мною, <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>,
              але деякі зображення та скріншоти можуть бути все ще російською мовою. Робота над локалізацією
              візуальних елементів триває. Дякую за розуміння!
            translator_unical_paper: |
              🌟 Унікальний контент! Ця сторінка створена мною, <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>,
              спеціально для доповнення оригінального керівництва. Вона містить інформацію, якої немає в російській версії,
              і покликана допомогти україномовним розробникам краще опанувати aiogram 3.x. Буду радий вашим відгукам та пропозиціям!
            help_translation_cta: Допомогти з перекладом


# Custom
nav_name: "Оглавление"
